/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Memorial } from "./Memorial";
import { MemorialCountArgs } from "./MemorialCountArgs";
import { MemorialFindManyArgs } from "./MemorialFindManyArgs";
import { MemorialFindUniqueArgs } from "./MemorialFindUniqueArgs";
import { DeleteMemorialArgs } from "./DeleteMemorialArgs";
import { MemorialService } from "../memorial.service";
@graphql.Resolver(() => Memorial)
export class MemorialResolverBase {
  constructor(protected readonly service: MemorialService) {}

  async _memorialsMeta(
    @graphql.Args() args: MemorialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Memorial])
  async memorials(
    @graphql.Args() args: MemorialFindManyArgs
  ): Promise<Memorial[]> {
    return this.service.memorials(args);
  }

  @graphql.Query(() => Memorial, { nullable: true })
  async memorial(
    @graphql.Args() args: MemorialFindUniqueArgs
  ): Promise<Memorial | null> {
    const result = await this.service.memorial(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Memorial)
  async deleteMemorial(
    @graphql.Args() args: DeleteMemorialArgs
  ): Promise<Memorial | null> {
    try {
      return await this.service.deleteMemorial(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
